// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


export interface AppData {
    "macros": Macro[] | null;
}

export interface Macro {
    "id": string;
    "disabled": boolean;
    "name": string;
    "activation_keys": number[] | null;
    "type": MacroType;
    "actions": MacroAction[] | null;
    "include_title": string[] | null;
}

export interface MacroAction {
    "id": string;
    "keys": number[] | null;
    "delay": number;
}

export enum MacroType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    MacroTypeSequence = 0,
    MacroTypeToggle = 1,
    MacroTypeHold = 2,
};
