// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syscall$0 from "../../../syscall/models.js";

export interface WindowInfo {
    "handle": syscall$0.Handle;
    "process": string;
    "iconBase64": string;
}
