// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


export enum Handle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    InvalidHandle = 18446744073709551615,
};
