// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

export function ReadAppData(): Promise<types$0.AppData> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3580827948) as any;
    return $resultPromise;
}

export function WriteAppData(data: types$0.AppData): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3113756703, data) as any;
    return $resultPromise;
}
