// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetData() {
  return window['go']['main']['App']['GetData']();
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}

export function UpdateData(arg1) {
  return window['go']['main']['App']['UpdateData'](arg1);
}
