// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetData():Promise<main.AppData>;

export function Shutdown():Promise<void>;

export function StartCapture():Promise<void>;

export function StopCapture():Promise<void>;

export function UpdateData(arg1:main.AppData):Promise<void>;
